# Generated by Django 6.0 on 2026-01-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0002_trait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statblock',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='statblock',
            name='date',
        ),
        migrations.AddField(
            model_name='statblock',
            name='Ag',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statblock',
            name='BS',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statblock',
            name='Dex',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statblock',
            name='Fel',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statblock',
            name='I',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statblock',
            name='Int',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statblock',
            name='S',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statblock',
            name='T',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statblock',
            name='Traits',
            field=models.ManyToManyField(to='statblocks.trait'),
        ),
        migrations.AddField(
            model_name='statblock',
            name='WP',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statblock',
            name='WS',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
