# Generated by Django 6.0 on 2026-01-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0003_rename_title_statblock_name_remove_statblock_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statblock',
            name='HP',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='Ag',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='BS',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='Dex',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='Fel',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='I',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='Int',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='S',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='T',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='WP',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='WS',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
