# Generated by Django 6.0 on 2026-01-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0004_statblock_hp_alter_statblock_ag_alter_statblock_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statblock',
            name='Sp',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
