# Generated by Django 6.0 on 2026-02-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0005_statblock_sp'),
    ]

    operations = [
        migrations.AddField(
            model_name='statblock',
            name='art',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='Traits',
            field=models.ManyToManyField(blank=True, to='statblocks.trait'),
        ),
    ]
